### PR TITLE
Add info on where to report bugs =)

### PR DESCRIPTION
**Pull request by kwando**

### CODE REVIEW

**Comment by solnic** [comment]
Thanks but could you s/bugs/issues/?

**Comment by kwando** [comment]
I'll squash this once I figure out how to do it in the web UI..

**Comment by daneb** [comment]
Hello

Please can we there be a place to ask questions or log issues?

**Comment by kwando** [comment]
@daneb Issues should be reported in the main ROM repo https://github.com/rom-rb/rom

**Comment by solnic** [comment]
huh totally missed that one

**Comment by kwando** [comment]
@solnic hehe, I was just looking though the README for that info xP

**Pull request merged**
